version: '3'

services:

  mall_keeper:
    build: .
    command: python code/app.py
    depends_on:
      - plant_shop
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - .:/code

  plant_shop:
    build: ./plants_shop
    ports:
      - "5000:5000"
    command: python app.py
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

